version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: UpstartDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    command: -configFiles=/flyway/conf/flyway-docker.conf migrate
    volumes:
      - ./flyway/upstart:/flyway/conf
      - ./flyway/upstart/migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network



volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge