-- Flyway migration: InitialCreate
-- Generated from EF Core migration on 2025-08-06 00:14:43
-- Description: InitialCreate

CREATE TABLE users (
id integer GENERATED BY DEFAULT AS IDENTITY,
first_name character varying(50) NOT NULL,
last_name character varying(50) NOT NULL,
email character varying(255) NOT NULL,
phone_number character varying(20),
date_of_birth timestamp with time zone,
social_security_number character varying(11),
address_line_1 character varying(100),
address_line_2 character varying(100),
city character varying(50),
state character varying(2),
zip_code character varying(10),
annual_income numeric(18,2),
employment_status character varying(50),
credit_score integer,
created_at timestamp with time zone NOT NULL,
updated_at timestamp with time zone NOT NULL,
CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE TABLE loans (
id integer GENERATED BY DEFAULT AS IDENTITY,
user_id integer NOT NULL,
loan_amount numeric(18,2) NOT NULL,
interest_rate numeric(5,2) NOT NULL,
term_months integer NOT NULL,
monthly_payment numeric(18,2) NOT NULL,
loan_purpose character varying(100) NOT NULL,
loan_status character varying(20) NOT NULL,
application_date timestamp with time zone NOT NULL,
approval_date timestamp with time zone,
disbursement_date timestamp with time zone,
maturity_date timestamp with time zone,
outstanding_balance numeric(18,2) NOT NULL,
total_payments_made numeric(18,2) NOT NULL,
next_payment_due_date timestamp with time zone,
payment_frequency character varying(20) NOT NULL,
late_fees numeric(18,2) NOT NULL,
origination_fee numeric(18,2) NOT NULL,
apr numeric(5,2),
loan_officer_notes character varying(1000),
created_at timestamp with time zone NOT NULL,
updated_at timestamp with time zone NOT NULL,
user_entity_id integer,
CONSTRAINT pk_loans PRIMARY KEY (id),
CONSTRAINT fk_loans_users_user_entity_id FOREIGN KEY (user_entity_id) REFERENCES users (id),
CONSTRAINT fk_loans_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_loans_user_entity_id ON loans (user_entity_id);
CREATE INDEX ix_loans_user_id ON loans (user_id);
CREATE UNIQUE INDEX ix_users_email ON users (email);
VALUES ('20250806051441_InitialCreate', '8.0.0');
