-- Flyway migration: Identities
-- Generated from EF Core migration on 2025-08-06 14:22:51
-- Description: Identities

CREATE TABLE users (
id integer GENERATED BY DEFAULT AS IDENTITY,
first_name character varying(50) NOT NULL,
last_name character varying(50) NOT NULL,
email character varying(255) NOT NULL,
password_hash character varying(255) NOT NULL,
phone_number character varying(20),
created_at timestamp with time zone NOT NULL,
updated_at timestamp with time zone NOT NULL,
CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE TABLE polls (
id integer GENERATED BY DEFAULT AS IDENTITY,
poll_guid character varying(36) NOT NULL,
user_id integer NOT NULL,
question character varying(500) NOT NULL,
is_active boolean NOT NULL,
is_multiple_choice boolean NOT NULL,
expires_at timestamp with time zone,
created_at timestamp with time zone NOT NULL,
updated_at timestamp with time zone NOT NULL,
CONSTRAINT pk_polls PRIMARY KEY (id),
CONSTRAINT fk_polls_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE TABLE poll_answers (
id integer GENERATED BY DEFAULT AS IDENTITY,
poll_id integer NOT NULL,
answer_text character varying(500) NOT NULL,
display_order integer NOT NULL,
created_at timestamp with time zone NOT NULL,
updated_at timestamp with time zone NOT NULL,
CONSTRAINT pk_poll_answers PRIMARY KEY (id),
CONSTRAINT fk_poll_answers_polls_poll_id FOREIGN KEY (poll_id) REFERENCES polls (id) ON DELETE CASCADE
);
CREATE TABLE poll_stats (
id integer GENERATED BY DEFAULT AS IDENTITY,
poll_id integer NOT NULL,
poll_answer_id integer NOT NULL,
user_id integer NOT NULL,
selected_at timestamp with time zone NOT NULL,
CONSTRAINT pk_poll_stats PRIMARY KEY (id),
CONSTRAINT fk_poll_stats_poll_answers_poll_answer_id FOREIGN KEY (poll_answer_id) REFERENCES poll_answers (id) ON DELETE CASCADE,
CONSTRAINT fk_poll_stats_polls_poll_id FOREIGN KEY (poll_id) REFERENCES polls (id) ON DELETE CASCADE,
CONSTRAINT fk_poll_stats_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX ix_poll_answers_poll_id ON poll_answers (poll_id);
CREATE INDEX ix_poll_stats_poll_answer_id ON poll_stats (poll_answer_id);
CREATE UNIQUE INDEX ix_poll_stats_poll_id_user_id ON poll_stats (poll_id, user_id);
CREATE INDEX ix_poll_stats_user_id ON poll_stats (user_id);
CREATE UNIQUE INDEX ix_polls_poll_guid ON polls (poll_guid);
CREATE INDEX ix_polls_user_id ON polls (user_id);
CREATE UNIQUE INDEX ix_users_email ON users (email);
VALUES ('20250806192249_Identities', '8.0.0');
